# Generated by Django 5.2.8 on 2025-11-18 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nasab_users', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سریال')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='مدت گارانتی (ماه)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نصب')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('installer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nasab_users.installer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
