# Generated by Django 5.2.8 on 2025-12-20 13:59

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nasab_users', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='مدت گارانتی (ماه)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نصب')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس 1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهرستان')),
                ('serial_number', models.CharField(max_length=50, verbose_name='شماره سریال محصول')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='مدت گارانتی (ماه)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('installer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nasab_users.installer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to=core.models.upload_installation_image)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.installation')),
            ],
        ),
    ]
