# Generated by Django 5.2.8 on 2025-12-20 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='address_2',
        ),
        migrations.AddField(
            model_name='installation',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='installation',
            name='model_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='نام مدل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره سریال'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
