# Generated by Django 5.2.8 on 2025-11-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='product',
        ),
        migrations.AddField(
            model_name='installation',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
