# Generated by Django 5.2.8 on 2025-11-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_installation_product_installation_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='count',
            field=models.IntegerField(default=1, max_length=10, verbose_name='تعداد محصولات'),
            preserve_default=False,
        ),
    ]
